# Generated by Django 4.2.23 on 2025-06-25 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('gorsel', models.ImageField(upload_to='urun_resimleri/')),
            ],
        ),
        migrations.CreateModel(
            name='Teklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_kimlik_no', models.CharField(max_length=11)),
                ('cep_telefonu', models.CharField(max_length=20)),
                ('eposta', models.EmailField(max_length=254)),
                ('belge', models.FileField(blank=True, null=True, upload_to='teklif_belgeleri/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.urun')),
            ],
        ),
    ]
