# Generated by Django 4.2.23 on 2025-06-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urun',
            old_name='ad',
            new_name='sigorta_tipi',
        ),
    ]
