# Generated by Django 4.2.23 on 2025-06-26 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunler', '0002_rename_ad_urun_sigorta_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklif',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='TeklifCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField()),
                ('pesin_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taksit_sayisi', models.IntegerField()),
                ('taksitli_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eposta_gonderildi', models.BooleanField(default=False)),
                ('gonderim_tarihi', models.DateTimeField(blank=True, null=True)),
                ('eposta_gonderen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teklif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='urunler.teklif')),
            ],
        ),
    ]
