# Generated by Django 4.2.23 on 2025-06-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_teklif_created_at_teklifcevap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigortaSirketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('sira', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
        migrations.AddField(
            model_name='teklifcevap',
            name='sigorta_sirketi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.sigortasirketi'),
        ),
    ]
