# Generated by Django 4.2.23 on 2025-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_sigortasirketi_teklifcevap_sigorta_sirketi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teklifcevap',
            name='sira',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
