# Generated by Django 4.2.23 on 2025-06-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_alter_teklifcevap_sira'),
    ]

    operations = [
        migrations.AddField(
            model_name='teklif',
            name='ad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='teklif',
            name='soyad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='teklif',
            name='tc_kimlik_no',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='T.C. Kimlik No'),
        ),
    ]
